# Generated by Django 6.0.2 on 2026-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
